version: '3'
services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "5201:5201"

  frontend:
    build:
      context: ./Frontend/my-app
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
